### ISSUE TITLE
The pretrained ckpt of spformer.

### ISSUE THREAD

**Issue by peoplelu** [VinAIResearch/GaPro#1]
Hello, I would like to know where the pretrained ckpt of spformer you are using comes from, can you share it, thank you very much!

**Comment by ngoductuanlhp** [comment]
To pretrain the sparse U-net backbone of SPFormer, we add the semantic head and offset head (as in [SoftGroup](https://github.com/thangvubk/SoftGroup) or [ISBNet](https://github.com/VinAIResearch/ISBNet)) and train it with the pseudo labels. You can find the checkpoint [here](https://drive.google.com/file/d/1j3h1RtEt4vISlO5e0FKVxTFw4NlnvUXI/view?usp=sharing).
